name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Validate Secrets
        run: |
          echo "Username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Password: ${{ secrets.DOCKER_PASSWORD }}****"

      - name: Build Docker Image
        run: docker build -t zunsod/proshop-backend .

      - name: Push Docker Image to Docker Hub
        run: docker push zunsod/proshop-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Image from Docker Hub
        run: docker pull zunsod/proshop-backend:latest

      - name: Stop and Remove Old Container
        run: docker rm -f proshop-backend-container || true

      - name: Run Docker Container with .env File
        run: |
          docker run -d \
          --name proshop-backend-container \
          -p 5000:5000 \
          --env-file .env \
          zunsod/proshop-backend:latest
