name: Deploy Node Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t zunsod/proshop-backend .

      - name: Publish Image to docker hub
        run: docker push zunsod/proshop-backend:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Pull image from docker hub
        run: docker pull zunsod/proshop-backend:latest

      - name: Stop and remove existing container
        run: |
          docker stop proshop-backend-container || true
          docker rm proshop-backend-container || true

      - name: Run docker container
        run: docker run -d -p 5000:5000 --name proshop-backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' zunsod/proshop-backend:latest
